/* 유저가 작성한 모든 식단 불러오기 */
export const GET_MEALPLANS_REQUEST = 'GET_MEALPLANS_REQUEST'
export const GET_MEALPLANS_SUCCESS = 'GET_MEALPLANS_SUCCESS'
export const GET_MEALPLANS_FAIL = 'GET_MEALPLANS_FAIL'

/* 추천레시피 불러오기 */
export const GET_RECOMMAND_REQUEST = 'GET_RECOMMAND_REQUEST'
export const GET_RECOMMAND_SUCCESS = 'GET_RECOMMAND_SUCCESS'
export const GET_RECOMMAND_RESET = 'GET_RECOMMAND_RESET'
export const GET_RECOMMAND_FAIL = 'GET_RECOMMAND_FAIL'


/* 일별 식단 불어오기 */
export const GET_MEALPLAN_REQUEST = 'GET_MEALPLAN_REQUEST'
export const GET_MEALPLAN_SUCCESS = 'GET_MEALPLAN_SUCCESS'
export const GET_MEALPLAN_FAIL = 'GET_MEALPLAN_FAIL'

/* 식단추가하기 */
export const NEW_MEALPLAN_REQUEST = 'NEW_MEALPLAN_REQUEST'
export const NEW_MEALPLAN_SUCCESS = 'NEW_MEALPLAN_SUCCESS'
export const NEW_MEALPLAN_RESET = 'NEW_MEALPLAN_RESET'
export const NEW_MEALPLAN_FAIL = 'NEW_MEALPLAN_FAIL'

/* 식단 수정하기 */
export const EDIT_MEALPLAN_REQUEST = ''
export const EDIT_MEALPLAN_SUCCESS = ''
export const EDIT_MEALPLAN_FAIL = ''

/* 식단 삭제하기 */
export const DELETE_MEALPLAN_REQUEST = 'DELETE_MEALPLAN_REQUEST'
export const DELETE_MEALPLAN_SUCCESS = 'DELETE_MEALPLAN_SUCCESS'
export const DELETE_MEALPLAN_RESET = 'DELETE_MEALPLAN_RESET'
export const DELETE_MEALPLAN_FAIL= 'DELETE_MEALPLAN_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'