/* 모든레시피 불러오기 */
export const ALL_RECIPES_REQUEST = 'ALL_RECIPES_REQUEST'
export const ALL_RECIPES_SUCCESS = 'ALL_RECIPES_SUCCESS'
export const ALL_RECIPES_FAIL = 'ALL_RECIPES_FAIL'

/* 레시피 불러오기 */
export const GET_RECIPE_REQUEST = 'GET_RECIPE_REQUEST'
export const GET_RECIPE_SUCCESS = 'GET_RECIPE_SUCCESS'
export const GET_RECIPE_FAIL = 'GET_RECIPE_FAIL'
