/* 모든 마이레시피 불러오기 */
export const GET_MYECIPES_REQUEST = 'GET_MYECIPES_REQUEST'
export const GET_MYECIPES_SUCCESS = 'GET_MYECIPES_SUCCESS'
export const GET_MYECIPES_FAIL = 'GET_MYECIPES_FAIL'

/* 마이레시피 추가하기 */
export const NEW_MYRECIPE_REQUEST = 'NEW_MYRECIPE_REQUEST'
export const NEW_MYRECIPE_SUCCESS = 'NEW_MYRECIPE_SUCCESS'
export const NEW_MYRECIPE_FAIL = 'NEW_MYRECIPE_FAIL'

/* 마이레시피 수정하기 */
export const EDIT_MYRECIPE_REQUEST  = 'EDIT_MYRECIPE_REQUEST'
export const EDIT_MYRECIPE_SUCCESS = 'EDIT_MYRECIPE_SUCCESS'
export const EDIT_MYRECIPE_FAIL = 'EDIT_MYRECIPE_FAIL'

/* 마이레시피 삭제하기 */
export const DELETE_MYRECIPE_REQUEST = 'DELETE_MYRECIPE_REQUEST'
export const DELETE_MYRECIPE_SUCCESS = 'DELETE_MYRECIPE_SUCCESS'
export const DELETE_MYRECIPE_RESET = 'DELETE_MYRECIPE_RESET'
export const DELETE_MYRECIPE_FAIL = 'DELETE_MYRECIPE_FAIL'

/* 모든 좋아요한 레시피 불러오기 */
export const GET_LIKELIST_REQUEST = 'GET_LIKELIST_REQUEST'
export const GET_LIKELIST_SUCCESS = 'GET_LIKELIST_SUCCESS'
export const GET_LIKELIST_FAIL = 'GET_LIKELIST_FAIL'

/* 유저 정보 불러오기 */
export const GET_USERINFO_REQUEST = 'GET_USERINFO_REQUEST'
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS'
export const GET_USERINFO_FAIL = 'GET_USERINFO_FAIL'

/* 유저 정보 수정하기 */
export const EDIT_USERINFO_REQUEST = 'EDIT_USERINFO_REQUEST'
export const EDIT_USERINFO_SUCCESS = 'EDIT_USERINFO_SUCCESS'
export const EDIT_USERINFO_FAIL = 'EDIT_USERINFO_FAIL'

/* 유저 계정 삭제하기 */
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

